# fly.toml app configuration file generated for imersao-alura-linguagens on 2023-05-13T04:34:48-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "imersao-alura-linguagens"
primary_region = "gru"

[build]
  image = "kaue13/imersao-alura-linguagens:linguagens-api-0.0.1-SNAPSHOT"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
